### ISSUE TITLE
What about a much larger collection?

### ISSUE THREAD

**Issue by skinkie** [mdeff/fma#1]
Hi, as radio station we have a much larger collection of lossless encoded audio (FLAC). Would it be interesting to see the performance on our collection?

**Comment by mdeff** [comment]
Hi, that sounds indeed very interesting. Not only to see the performance, but more importantly to train and evaluate. The problem with music is to be able to distribute the audio to researchers, because of copyright. Are you able to redistribute your collection ? Otherwise, how do you imagine to provide access ?

**Comment by skinkie** [comment]
So Dutch law would exclude education and scientific research. But if I would offer the set, including computing power. I would like to keep the contribution anonymous at this time :)

> 5 Onder een voordracht, op- of uitvoering of voorstelling in het openbaar wordt niet begrepen die welke uitsluitend dient tot het onderwijs dat vanwege de overheid of vanwege een rechtspersoon zonder winstoogmerk wordt gegeven, voor zover de voordracht, op- of uitvoering of voorstelling deel uitmaakt van het schoolwerkplan of leerplan voor zover van toepassing, of tot een wetenschappelijk doel.

**Comment by mdeff** [comment]
Would this be valid worldwide for your entire collection ? I'm not knowledgeable with copyright laws. The thing is I don't want to release it and then for copyright holders to come down on us and force us to remove everything. That would waste everybody's time. The songs hosted by FMA are under a permissive Creative Commons license which allows redistribution, so we are sure.

BTW, how many songs and what kind of songs are we talking about ?
