### ISSUE TITLE
Error while loading tracks.csv

### ISSUE THREAD

**Issue by izidov** [mdeff/fma#17]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-4c9081cc90a8> in <module>()
      3 
      4 # Load metadata and features.
----> 5 tracks = utils.load('tracks.csv')
      6 genres = utils.load('genres.csv')
      7 features = utils.load('features.csv')

~\Desktop\ML\DeepAudioClassification-master - Copy\utils.py in load(filepath)
    201                    ('track', 'genres_top')]
    202         for column in COLUMNS:
--> 203             tracks[column] = tracks[column].map(ast.literal_eval)
    204 
    205         COLUMNS = [('track', 'date_created'), ('track', 'date_recorded'),

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2055             if isinstance(i, slice):
   2056                 return self[i]
-> 2057             else:
   2058                 label = self.index[i]
   2059                 if isinstance(label, Index):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_multilevel(self, key)
   2099                 # a 0-len ndarray. This is effectively catching
   2100                 # a numpy error (as numpy should really raise)
-> 2101                 values = self._data.iget(i)
   2102 
   2103                 if index_len and not len(values):

~\Anaconda3\lib\site-packages\pandas\indexes\multi.py in get_loc(self, key, method)

pandas\index.pyx in pandas.index.IndexEngine.get_loc (pandas\index.c:4433)()

pandas\index.pyx in pandas.index.IndexEngine.get_loc (pandas\index.c:4279)()

pandas\src\hashtable_class_helper.pxi in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13742)()

pandas\src\hashtable_class_helper.pxi in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13696)()

KeyError: ('track', 'genres_top')

Error while loading csv files
Does anyone know fix?

**Comment by izidov** [comment]
NVM fixed it

**Comment by mdeff** [comment]
#9 again

**Comment by subhamkrai** [comment]
i'm getting error "utils has no module load" but i have installed utils

**Comment by subhamkrai** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-19-9174df1f7ea7> in <module>
      3 
      4 # Load metadata and features.
----> 5 tracks = utils.load('tracks.csv')
      6 '''genres = utils.load('genres.csv')
      7 features = utils.load('features.csv')

AttributeError: module 'utils' has no attribute 'load'

**Comment by mdeff** [comment]
The `utils` module is the `utils.py` file in this repository. Not something to be installed. I suspect you installed [utils from PyPI](https://pypi.org/project/utils/)?
