### ISSUE TITLE
improper data distribution in fma-medium as well as need for seperate metadata 

### ISSUE THREAD

**Issue by mohitbindal10** [mdeff/fma#19]
i downloaded the fma_medium dataset it has 161 folders with almost 1000 30's tracks each but there in no information as what genres they belong as description for fma_medium states it should have 25000 tracks for 16 unbalanced genres and if it a subset of fma_large the metadata file for genres has more than 161 genres for me to able to match

**Comment by mdeff** [comment]
The folders in `fma_medium` have no semantic meanings. They are just ways to avoid having 100k files in a single folder.

You should download the `fma_metadata.zip` file which contains all the metadata. Then look at the [usage notebook](https://nbviewer.jupyter.org/github/mdeff/fma/blob/outputs/usage.ipynb) for guidance to manipulate that metadata.
