### ISSUE TITLE
How can I split the fma-small dataset with genres?

### ISSUE THREAD

**Issue by DennisShaw** [mdeff/fma#20]
I can not find a way to split the source audio zip to 8 genres with 1000 tracks.I can't find a file to help me do this.Would you mind helping me? Please...Thanks

**Comment by mdeff** [comment]
You should download the `fma_metadata.zip` file which contains all the metadata. Then look at the [usage notebook](https://nbviewer.jupyter.org/github/mdeff/fma/blob/outputs/usage.ipynb) for guidance to manipulate that metadata.

**Comment by DennisShaw** [comment]
But the fifth part of usage.ipynb( Genre classification) is not finished yet.

**Comment by mdeff** [comment]
Look at the [baselines notebook](https://nbviewer.jupyter.org/github/mdeff/fma/blob/outputs/baselines.ipynb) for more code about genre classification.

**Comment by ableabhinav** [comment]
Hey, were

> I can not find a way to split the source audio zip to 8 genres with 1000 tracks.I can't find a file to help me do this.Would you mind helping me? Please...Thanks

Hey, were you finally able to split the audios to 8 genres? If so, could you please help me out do the same?

**Comment by ableabhinav** [comment]
Or should I open another issue for this?

**Comment by drscotthawley** [comment]
I posted a gist to do this at
https://gist.github.com/drscotthawley/eb4ffb1ec4de29632403c1db396e419a
