### ISSUE TITLE
What are the eight genres in the FMA_Small Dataset?

### ISSUE THREAD

**Issue by DennisShaw** [mdeff/fma#22]
What are the eight genres in the FMA_Small Dataset?Thanks.

**Comment by mdeff** [comment]
The eight genres are:
1. Rock
2. Electronic
3. Experimental
4. Hip-Hop
5. Folk
6. Instrumental
7. Pop
8. International

**Comment by microwavePC** [comment]
In the fma_small.zip, there are 156 folders, contains mp3 files.
I'd like to know which file is which genre.

Thanks.

**Comment by mdeff** [comment]
The 156 folders have no meaning. They are there to avoid having all the files in a single directory, which causes issues with some filesystems.

You'll found the genre for each file in the `tracks.csv` file (zipped in `fma_metadata.zip`). Please look at the [usage notebook](https://nbviewer.jupyter.org/github/mdeff/fma/blob/outputs/usage.ipynb).
