### ISSUE TITLE
host on cloud computing provider

### ISSUE THREAD

**Issue by danmackinlay** [mdeff/fma#26]
A suggestion - I notice there are a few open issues about outdated data version, so I presume the hosting of this data is inconvenient to update. As such i might be worth hosting the data somewhere else.

according to the [FAQ](https://msropendata.com/faq), Microsoft Research Open Data will host data sets up to 250gb. Amazon ad probably google offer similar schemes.

**Comment by danmackinlay** [comment]
Amazon's AWS also hosts data sets and has a [formal submission procedure](https://aws.amazon.com/opendata/public-datasets/) for new data sets.

**Comment by dvolgyes** [comment]
Or maybe on https://zenodo.org/ ?
It is a Swiss (CERN based) data repository for scientific data sets, it gives DOI, you can link exisiting publications to it, and it has no space limit. (By default, it is 50GB, but you can contact them by email, and they will lift the limit for the given upload.)

**Comment by dvolgyes** [comment]
And Zenodo has a simple, usable API.

**Comment by mdeff** [comment]
Thanks for the suggestions! AWS and Microsoft are potential providers. I like Zenodo, but when I contacted them in May 2017 about hosting the FMA they answered: "Unfortunately the data sizes you mentioned are above of what we can accept." Another option is torrents (#32), though I don't know how convenient that is in general, and how to ensure that there's always one peer up.

The current hosting is not inconvenient to update, but I think that we should strive to update as infrequently as possible. One problem is that published results are only comparable on the same data, so every update makes things more difficult to compare.

I've [documented the known issues in the README](https://github.com/mdeff/fma#history) and in meta-issue #41. Hope that helps for the time being.
