### ISSUE TITLE
Issues while unzipping fma_small.zip

### ISSUE THREAD

**Issue by VikramShenoy97** [mdeff/fma#30]
When I unzip the file on my MacBook I get only around 1945 tracks instead of the 8000 mentioned.
The track "048367" is causing an issue while unzipping and it stops over there.
I've used the default application, Keka and The Unarchiver but all three are resulting in the same issue. 
I tried unzipping with 7zip on a windows OS but I'm still getting the same 1945 tracks since it stops at track "048367"

Anybody else facing the same problem?

**Comment by joangerard** [comment]
Download and install [Keka](https://www.keka.io/en/). Then use this tool to unzip file.
