### ISSUE TITLE
Unable to download features.csv without downloading whole dataset

### ISSUE THREAD

**Issue by 0xD34DC0DE** [mdeff/fma#33]
Id like to just download the features.csv file without downloadind the whole 7.2 GiB (I don't need the 30s samples) is there a way to do it without downloading the whole dataset since my connection is kinda slow ?

**Comment by ciotog** [comment]
As per the docs:
All metadata and features for all tracks are distributed in [fma_metadata.zip](https://os.unil.cloud.switch.ch/fma/fma_metadata.zip) (342 MiB).

**Comment by 0xD34DC0DE** [comment]
Thank you and apologies from me
