### ISSUE TITLE
Unable to download fma_full.zip

### ISSUE THREAD

**Issue by TariqAHassan** [mdeff/fma#38]
## Overview

The download of `fma_full.zip` stops before completion.

## Steps to Reproduce

```bash
# From the README
curl -O https://os.unil.cloud.switch.ch/fma/fma_full.zip
```

which, after a while, gives something like this:

```bash
transfer closed with n bytes remaining to read
```

Any advice/help would be greatly appreciated :)

**Comment by mdeff** [comment]
Is that still an issue? I expect many people downloaded it in the meantime.

**Comment by TariqAHassan** [comment]
It's working now. Thank you :)
