### ISSUE TITLE
update technical metadata

### ISSUE THREAD

**Issue by keunwoochoi** [mdeff/fma#4]
As title says. Probably it's not valid?

**Comment by tae-jun** [comment]
👍 In my case, it's only 1.8KB

**Comment by mdeff** [comment]
Indeed. Looks like the clipping failed. I have:
* `fma_full/133/133297.mp3`, 4546530 bytes, sha1 d6a6aa0d0a4264e7679aaca3c3cc4c67127143b7
* `fma_large/133/133297.mp3`, 1752 bytes, sha1 19c8a6a03db7df5768cc0a424344cb2441875cb0

**Comment by mdeff** [comment]
Found the problem. The metadata, scraped from the [FMA API](https://freemusicarchive.org/api), claims the song is 600 seconds long, while `ffmpeg -i 133297.mp3  -f null -` tells us it's about 01:53.56. The `trim_audio()` function in `creation.py` is clipping 30 seconds in the middle of the song, that is from 285s to 315s for this particular file. But that is out of the song, which is 114s long.

It's not the first time I see an error in the reported song length. The solution is to extract the duration from the file with ffmpeg and update the metadata. I should do that at some point.

**Comment by tae-jun** [comment]
@mdeff You are the best! 👍

**Comment by mdeff** [comment]
Haha thanks @tae-jun :)

While at this, we should collect the following *technical metadata* to be included in `fma_metadata.csv`:
* Bit rate
* Number of channels
* Sample rate
* Number of samples
* Duration is a function of the above two

I'll probably do that for the final release. If somebody wants​ to help, you're welcome. :)

**Comment by chiwanpark** [comment]
I just found same error in `fma_small/108/108925.mp3`.

**Comment by mdeff** [comment]
Thanks all for reporting. :) I will fix this problem for the v1 release. Don't hesitate to open issues for other problems if you find some.

**Comment by mohitbindal10** [comment]
i downloaded the fma_medium dataset it has 161 folders with almost 1000 30's tracks each but there in no information as what genres they belong as description for fma_medium states it should have 25000 tracks for 16 unbalanced genres and if it a subset of fma_large the metadata file for genres has more than 161 genres for me to able to match

**Comment by mdeff** [comment]
Please open a separate issue. Thanks
