### ISSUE TITLE
How to find the title metadata of a particular file in fma_large?

### ISSUE THREAD

**Issue by kernelogic** [mdeff/fma#48]
Hello I am trying to browse through the archive and having a hard time to understand the metadata.zip.

For example if I want to get the title of file 020/020001.mp3 in the fma_large.zip, how can I locate it in the tracks.csv?

**Comment by mdeff** [comment]
Please look at the [`usage.ipynb`](https://nbviewer.jupyter.org/github/mdeff/fma/blob/outputs/usage.ipynb) notebook which shows how the metadata is organized.

> For example if I want to get the title of file 020/020001.mp3 in the fma_large.zip, how can I locate it in the tracks.csv?

It's the row that has a `track_id` of `020001`.

**Comment by mdeff** [comment]
Yes. Filenames are all 6 digits because some systems don't properly order files otherwise (I guess that's when the name is treated as a string).
