### ISSUE TITLE
Selecting Subset of Multiple Genres

### ISSUE THREAD

**Issue by dylanprins** [mdeff/fma#56]
Hi! I'm trying to figure out how i can obtain a subset of tracks using a list of genres. I picked a couple of genres. using a list like ["genre1", "genre2", ...] i want to slice the multiindex tracks so i only have the metadata for the tracks of those genres.

With tracks i mean the result you get when loading the tracks.csv.

This way i can feed tracks['track', 'genres_all'] too the fit transform/LabelBinarizer but now i only have the tracks with the genres i picked.

Kind regards,
Dylan.

**Comment by mdeff** [comment]
Hi, thanks for your interest. I'm however unable to code on your behalf. Please look at the [notebooks](https://github.com/mdeff/fma#code) for usage examples.

**Comment by mdeff** [comment]
Feel however free to paste your solution here. That could be useful for others.
