### ISSUE TITLE
The genre ID in FMA_large

### ISSUE THREAD

**Issue by liu2231665** [mdeff/fma#6]
Hello. I am going to use the FMA_large dataset. I notice that the dataset is separated into 1-155 in order, which is not matched with genre_id. Hence, I wander what should I do to get the exact genre of each folder??

**Comment by liu2231665** [comment]
umh.... I found it on the csv file... Sorry for this mistake....

**Comment by mdeff** [comment]
Hello! Sorry for the late reply. Indeed, the genres are the `genres`, `genres_all` and `genre_top` columns (see the paper for what each means) in `tracks.csv`. The folders' names are just the first three digits of the `track_id`. There sole purpose was to split the files among several folders with less than 1000 files in each.
