### ISSUE TITLE
Lossless music format

### ISSUE THREAD

**Issue by gogo9th** [mdeff/fma#60]
Hi,

Thanks very much for this great dataset. 
I am working on a research project that requires lossless music files as input. I wonder if there is any way for us (or me) to get a .wav or .flac lossless version of your dataset by any chance.

**Comment by kikohs** [comment]
Hello,
No unfortunately - files are uploaded by artists with compression.

**Comment by mdeff** [comment]
Duplicate of #55. Thanks for your interest!
