### ISSUE TITLE
implementing

### ISSUE THREAD

**Issue by l3lackwood** [mdeff/fma#7]
i have tried  different ways to  implement this  codes but every time i found a new error 
can you help me how can i use these codes 
i had installed python 3.5 and all of packages in requirements after that i run the  creation and i found this error :
C:\Users\l3lackwood\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\dotenv\main.py:24: UserWarning: Not loading  - it doesn't exist.
  warnings.warn("Not loading %s - it doesn't exist." % dotenv_path)
Traceback (most recent call last):
  File "F:\farideh\python\WinPython-32bit-3.5.3.1Qt5\notebooks\genre\fma-master\creation.py", line 232, in <module>
    if sys.argv[1] == 'metadata':
IndexError: list index out of range

what should i do ?

**Comment by mdeff** [comment]
You need to add the path to the audio files, i.e. where you decompressed one of the `fma_*.zip` files containing `mp3`, in a `.env` file, like `AUDIO_DIR=/path/to/audio` (point 5 of the [usage instructions](https://github.com/mdeff/fma#usage)). That file should be in the root directory, i.e. where the `creation.py` file resides. Without this, the `creation.py` script does not know where to search for those audio files.

**Comment by mdeff** [comment]
You then have to pass parameters to the `creation.py` script, e.g. `./creation.py metadata`. Please look at the `creation.ipynb` notebook. Note that this script is however only useful to recreate the dataset.
