### ISSUE TITLE
Folder structure in fam_large.zip

### ISSUE THREAD

**Issue by gkv91** [mdeff/fma#72]
Hi,

Thanks for providing the dataset.  I am wondering what is the "002" in the "fma_large/002/002624.mp3" indicate?  

Thanks

**Comment by mdeff** [comment]
I grouped files in folders as some filesystems don't like having so many files under a single folder. The folder name is the first three digits of the filenames it contains.

**Comment by gkv91** [comment]
Thanks for the clarification.  Also, can you help me to find the corresponding Genre for each of the mp3 files in the fma_large? 

Thanks

**Comment by mdeff** [comment]
See the [`usage.ipynb`](https://nbviewer.jupyter.org/github/mdeff/fma/blob/outputs/usage.ipynb) notebook.
