### ISSUE TITLE
Malformed node error when using utils.load in Usage.ipynb

### ISSUE THREAD

**Issue by mjdebord** [mdeff/fma#9]
Hello, I am just going over the usage example but I am unable to load the track metadata using utils.py

The first error I had was a bad key error for column ('track', 'genres_top'), but I was able to fix that by noticing that the tracks.csv column name is actually 'genre_top' (no s). After fixing that I still have an issue with ast.literal eval. This is the error I am getting from the notebook:

>  ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-2-e2602eb7e710> in <module>()
>       3 
>       4 # Load metadata and features.
> ----> 5 tracks = utils.load('tracks.csv')
>       6 genres = utils.load('genres.csv')
>       7 features = utils.load('features.csv')
> 
> ~/projects/fma-stft/fma/utils.py in load(filepath)
>     202         for column in COLUMNS:
>     203             print("Column: {}".format(column))
> --> 204             tracks[column] = tracks[column].map(ast.literal_eval)
>     205 
>     206         COLUMNS = [('track', 'date_created'), ('track', 'date_recorded'),
> 
> ~/projects/fmaenv/lib/python3.5/site-packages/pandas/core/series.py in map(self, arg, na_action)
>    2311         else:
>    2312             # arg is a function
> -> 2313             new_values = map_f(values, arg)
>    2314 
>    2315         return self._constructor(new_values,
> 
> pandas/_libs/src/inference.pyx in pandas._libs.lib.map_infer()
> 
> /usr/lib/python3.5/ast.py in literal_eval(node_or_string)
>      82                 return left - right
>      83         raise ValueError('malformed node or string: ' + repr(node))
> ---> 84     return _convert(node_or_string)
>      85 
>      86 
> 
> /usr/lib/python3.5/ast.py in _convert(node)
>      81             else:
>      82                 return left - right
> ---> 83         raise ValueError('malformed node or string: ' + repr(node))
>      84     return _convert(node_or_string)
>      85 
> 
> ValueError: malformed node or string: <_ast.BinOp object at 0x7f25f0a53208>

The error occurs when processing column ('track', 'genre_top') in ' tracks[column] = tracks[column].map(ast.literal_eval)' , the other columns work normally. I downloaded the fma_metadata.zip and fma_small.zip from the provided links, and ensured that the sha1hash's were correct.

*I've just tried using python 3.6.0 using the suggested method in the readme, but I still have the same issue.

**Comment by mdeff** [comment]
Your issue is caused by changes into the data format I made toward the release of v1. For now the available data is the revision rc1. You'll find code working with that revision by doing `git checkout tags/rc1`.

**Comment by mjdebord** [comment]
Hi, thank you for the quick response. That seemed to be my only issue.

**Comment by yuroitaki** [comment]
hi there, i've checked out rc1 but am still facing the same issue with rc1 track.csv:

Traceback (most recent call last):
  File "/mnt/c/Users/TTCTAUTE/Documents/src/fma/test-script-1.py", line 20, in <module>
    tracks = utils.load('{}/tracks.csv'.format(AUDIO_META_DIR))
  File "/mnt/c/Users/TTCTAUTE/Documents/src/fma/utils.py", line 202, in load
    tracks[column] = tracks[column].map(ast.literal_eval)
  File "/mnt/c/Users/TTCTAUTE/Documents/src/venv_notebook/lib/python3.6/site-packages/pandas/core/series.py", line 3382, in map
    arg, na_action=na_action)
  File "/mnt/c/Users/TTCTAUTE/Documents/src/venv_notebook/lib/python3.6/site-packages/pandas/core/base.py", line 1218, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: nan

**Comment by mdeff** [comment]
@yuroitaki I can't reproduce. What's your OS, version of python, numpy, and pandas?
